<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../AroundTheWorld.DomainModels/AroundTheWorld.DomainModels.csproj" />
    <ProjectReference Include="../AroundTheWorld.Abstractions/AroundTheWorld.Abstractions.csproj" />
    <ProjectReference Include="../AroundTheWorld.Database/AroundTheWorld.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <EnableDefaultResourceItems>false</EnableDefaultResourceItems>    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
